### ISSUE TITLE
Potential removal/archiving of bbmle from CRAN

### ISSUE THREAD

**Issue by mclements** [bbolker/bbmle#32]
CRAN has sent a notice that `bbmle` may be removed from CRAN in the near future due to "no update from the [bbmle] maintainer thus far". The package check link is [here](https://cran.r-project.org/web/checks/check_results_bbmle.html), which gives an error under the heading `noSuggests`. There is a long [log file](https://www.stats.ox.ac.uk/pub/bdr/noSuggests/bbmle.out), with an error at the end:

```
--- re-building ‘quasi.Rnw’ using knitr
Quitting from lines 152-157 (quasi.Rnw) 
Error: processing vignette 'quasi.Rnw' failed with diagnostics:
there is no package called 'AICcmodavg'
--- failed re-building ‘quasi.Rnw’

SUMMARY: processing the following file failed:
  ‘quasi.Rnw’

Error: Vignette re-building failed.
Execution halted
```

I cannot explain this error, because `AICcmodavg` is a suggested package (see https://github.com/bbolker/bbmle/blob/master/DESCRIPTION#L27) and `AICcmodavg` has not been removed from CRAN (see https://cran.r-project.org/package=AICcmodavg). 

A simple workaround would be to comment out lines 149-159 of https://github.com/bbolker/bbmle/blob/master/vignettes/quasi.Rnw#L149-L159. 

Can anyone else explain this error?

Sincerely, Mark.

**Comment by bbolker** [comment]
Hi @mclements: thanks for raising this.

You will have received my e-mail response to BDR.

A variety of points in no particular order:

- The e-mail from BDR (on 23 April) said "Please correct before 2022-05-07 to safely retain your package on CRAN."  I guess I read that as "on or before", but maybe CRAN feels that "before" means before 12:00:01 AM central European time on the specified day?
- I fixed the relevant issues (I think) in commit 918d335be65296 by wrapping the relevant code chunks with `if (require("AICcmodavg")) { ... }`
- BDR has recently implemented a `noSuggests` test platform whose explicit goal is to test packages with suggested packages missing to see if they are following the recommended practice from [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages)
- technically, a package that fails to build vignettes (only!) due to missing suggested packages does **not** violate the [CRAN repository policy](https://cran.r-project.org/web/packages/policies.html), which says:
    >  A package listed in ‘Suggests’ or ‘Enhances’ should be used conditionally **in examples or tests** if it cannot straightforwardly be installed on the major R platforms. (‘Writing R Extensions’ recommends that they are always used conditionally.) 

    However, it's rarely worth arguing with CRAN ...

**Comment by bbolker** [comment]
resolved.
